// SPDX-License-Identifier: MIT
//
// @zagents/host-github-actions — GitHub Actions host adapter. The 9th host,
// per ADR-033.
//
// GitHub Actions is "different in kind" from the eight interactive hosts:
// there's no human at the keyboard. Execution is triggered by a webhook
// (push, PR, issue comment, schedule); the operator is the runner; the
// gemini must complete a task autonomously, emit structured output, and
// exit cleanly.
//
// What the adapter emits (ADR-033 §Decision):
//   - .github/workflows/<name>.yml   — the default trigger workflow
//   - .github/actions/<name>/action.yml — a composite action manifest the
//     workflow calls, so the gemini logic is reusable across workflows
//   - install.md — wiring + permissions runbook
//
// Default-deny posture (ADR-022) is preserved but the ENFORCEMENT MECHANISM
// shifts from the in-process mcp-policy.json gate to the workflow's own
// `permissions:` block — least-privilege GITHUB_TOKEN scopes. The adapter
// emits `permissions:` as read-all + only the writes the policy's allow
// list implies, and a comment pointing at Environment protection rules for
// production-touching jobs.

import type { HostAdapter, HarnessSpec } from '@zagents/kernel';

export const HOST_NAME = 'github-actions' as const;

/** Slugify a gemini name into a safe workflow/action identifier. */
export function ghaSlug(name: string): string {
  return (name || 'gemini')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '') || 'gemini';
}

/**
 * Map the gemini permission policy onto a GitHub `permissions:` block.
 * Default-deny → start from `contents: read` and grant only what the
 * allow-list implies. We map a small, auditable set of allow tokens to
 * GitHub permission scopes; anything unmapped stays denied (omitted).
 */
export function permissionsBlock(spec: HarnessSpec): Record<string, string> {
  const allow = spec.permissions?.allow ?? [];
  const perms: Record<string, string> = { contents: 'read' };
  const has = (re: RegExp) => allow.some((a) => re.test(a));
  // PR / branch writes
  if (has(/pull[-_]?request|create[-_]?pr|push[-_]?branch|contents:write/i)) perms.contents = 'write';
  if (has(/pull[-_]?request|create[-_]?pr|pr[-_]?comment/i)) perms['pull-requests'] = 'write';
  if (has(/issue|label|triage/i)) perms.issues = 'write';
  if (has(/checks|status/i)) perms.checks = 'write';
  return perms;
}

/**
 * Build the trigger workflow YAML (.github/workflows/<name>.yml).
 * Triggers default to manual dispatch + issue-comment (the safest pair);
 * the comment notes how to add push / PR / schedule triggers.
 */
export function workflowYaml(spec: HarnessSpec): string {
  const slug = ghaSlug(spec.name);
  const perms = permissionsBlock(spec);
  const permLines = Object.entries(perms).map(([k, v]) => `  ${k}: ${v}`);
  return [
    `# GitHub Actions gemini: ${spec.name}`,
    spec.description ? `# ${spec.description}` : '# Autonomous agent gemini — runs on the GitHub Actions runner.',
    '#',
    '# Generated by zagents (host: github-actions, ADR-033). Edit the',
    '# triggers below to fit your workflow. Default: manual + issue-comment',
    '# (the safest pair). Uncomment push / pull_request / schedule as needed.',
    `name: ${slug}`,
    '',
    'on:',
    '  workflow_dispatch: {}',
    '  issue_comment:',
    '    types: [created]',
    '  # push:',
    '  #   branches: [main]',
    '  # pull_request: {}',
    '  # schedule:',
    "  #   - cron: '0 9 * * 1'",
    '',
    '# ADR-022 default-deny: start from contents:read; grant only what the',
    '# gemini policy allow-list implies. For production-touching jobs, gate',
    '# behind a GitHub Environment with required reviewers (Settings →',
    '# Environments) — the permissions block alone does not add human review.',
    'permissions:',
    ...permLines,
    '',
    'concurrency:',
    `  group: ${slug}-\${{ github.ref }}`,
    '  cancel-in-progress: false',
    '',
    'jobs:',
    `  ${slug}:`,
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@v4',
    `      - name: Run ${spec.name}`,
    `        uses: ./.github/actions/${slug}`,
    '        with:',
    '          # The composite action reads the event payload + emits',
    '          # structured output. Wire your model provider key here.',
    '          task: ${{ github.event.comment.body || github.event_name }}',
    '        env:',
    '          # ADR-044: provider-agnostic. Set whichever your gemini uses as a',
    '          # repo secret; unset ones are empty and the gemini ignores them.',
    '          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}',
    '          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}',
    '          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}',
    '',
  ].join('\n');
}

/**
 * Build the composite action manifest (.github/actions/<name>/action.yml).
 * Keeps the gemini logic reusable across multiple workflows.
 */
export function actionYaml(spec: HarnessSpec): string {
  const slug = ghaSlug(spec.name);
  const hasPrompt = !!spec.systemPrompt;
  const hasMcp = (spec.mcpServers?.length ?? 0) > 0;
  return [
    `# Composite action for the ${spec.name} gemini (ADR-033).`,
    '# Called by .github/workflows/' + slug + '.yml. Reusable across workflows.',
    `name: ${slug}`,
    `description: ${JSON.stringify(spec.description ?? 'Autonomous agent gemini')}`,
    'inputs:',
    '  task:',
    '    description: The task/prompt for the gemini to complete.',
    '    required: true',
    'outputs:',
    '  result:',
    '    description: Structured result emitted by the gemini.',
    '    value: ${{ steps.run.outputs.result }}',
    'runs:',
    '  using: composite',
    '  steps:',
    ...(hasMcp ? [
      // ADR-044: surface the gemini's MCP servers to the runner. The manifest
      // is emitted alongside the action; the entrypoint reads it to register
      // servers (the runner has no interactive `mcp add` step).
      '    - id: mcp',
      '      shell: bash',
      '      run: |',
      '        echo "MCP servers for this gemini:" && cat "$GITHUB_ACTION_PATH/mcp-servers.json"',
      '',
    ] : []),
    '    - id: run',
    '      shell: bash',
    '      run: |',
    `        echo "Running ${spec.name} gemini (non-interactive)…"`,
    ...(hasPrompt ? [
      '        # ADR-044: the gemini system prompt ships next to the action.',
      '        export HARNESS_SYSTEM_PROMPT="$(cat "$GITHUB_ACTION_PATH/SYSTEM.md")"',
    ] : []),
    '        # Replace with your gemini entrypoint. It MUST: read $TASK,',
    '        # complete autonomously, write a structured result to',
    '        # $GITHUB_OUTPUT as result=<json>, and exit 0 on success.',
    '        echo "result={\\"status\\":\\"ok\\",\\"task\\":\\"$TASK\\"}" >> "$GITHUB_OUTPUT"',
    '      env:',
    '        TASK: ${{ inputs.task }}',
    '',
  ].join('\n');
}

/** Per-host setup runbook. */
export function installRunbook(spec: HarnessSpec): string {
  const slug = ghaSlug(spec.name);
  const perms = permissionsBlock(spec);
  return [
    `# Installing ${spec.name} as a GitHub Actions gemini`,
    '',
    '## What landed',
    '',
    `- \`.github/workflows/${slug}.yml\` — the trigger workflow`,
    `- \`.github/actions/${slug}/action.yml\` — the reusable composite action`,
    '',
    '## Wire it up',
    '',
    '1. Commit both files to your repo on the default branch.',
    '2. Add your model-provider key as a repo secret:',
    '   `Settings → Secrets and variables → Actions → New repository secret`',
    '   (the workflow expects `ANTHROPIC_API_KEY`).',
    '3. Trigger it: `Actions → ' + slug + ' → Run workflow`, or comment on an',
    '   issue (the default `issue_comment` trigger).',
    '',
    '## Permissions (ADR-022 default-deny)',
    '',
    'The workflow grants only:',
    '',
    ...Object.entries(perms).map(([k, v]) => `- \`${k}: ${v}\``),
    '',
    'Anything not listed is denied. To widen, add the matching capability to',
    "the gemini policy's allow-list and re-scaffold — don't hand-edit the",
    'workflow, or `gemini mcp-scan` will flag the drift on your next PR.',
    '',
    '## Production safety',
    '',
    'For jobs that push branches or cut releases, gate the job behind a',
    'GitHub Environment with required reviewers',
    '(`Settings → Environments`). The `permissions:` block scopes the token;',
    'the Environment adds the human review the block cannot.',
  ].join('\n') + '\n';
}

export const adapter: HostAdapter = {
  name: HOST_NAME,
  generateConfig: (spec: HarnessSpec) => {
    const slug = ghaSlug(spec.name);
    const out: Record<string, string> = {
      [`.github/workflows/${slug}.yml`]: workflowYaml(spec),
      [`.github/actions/${slug}/action.yml`]: actionYaml(spec),
      'install.md': installRunbook(spec),
    };
    // ADR-044: ship the system prompt next to the action (read at runtime).
    if (spec.systemPrompt) {
      out[`.github/actions/${slug}/SYSTEM.md`] =
        `# ${spec.name}\n\n${spec.description ? spec.description + '\n\n' : ''}${spec.systemPrompt}\n`;
    }
    // ADR-044: ship the MCP server manifest so the runner can register them.
    if ((spec.mcpServers?.length ?? 0) > 0) {
      out[`.github/actions/${slug}/mcp-servers.json`] =
        JSON.stringify({ mcpServers: spec.mcpServers }, null, 2) + '\n';
    }
    return out;
  },
};

export default adapter;
