// iter 135 — `gemini plugin-init` backfill subcommand. The doctor WARN
// from iter 134 recommends this as the remediation for legacy harnesses
// that pre-date iter-131's .claude-plugin/plugin.json propagation.
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { existsSync, mkdtempSync, rmSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { pluginInitCmd } from '../src/plugin-init-cmd.js';

let dir: string;

beforeEach(async () => {
  dir = mkdtempSync(join(tmpdir(), 'plugin-init-'));
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

async function writeLegacyManifest(opts: { name?: string; description?: string; templateId?: string; domain?: string } = {}) {
  await mkdir(join(dir, '.gemini'), { recursive: true });
  const m = { meta: { name: opts.name ?? 'legacy-bot', description: opts.description ?? 'pre-iter-131 gemini', templateId: opts.templateId, domain: opts.domain } };
  await writeFile(join(dir, '.gemini', 'manifest.json'), JSON.stringify(m, null, 2), 'utf-8');
}

describe('gemini plugin-init', () => {
  it('FAILs when there is no .gemini/manifest.json', async () => {
    const r = await pluginInitCmd([dir]);
    expect(r.code).toBe(1);
    expect(r.lines.some((l) => l.includes('no .gemini/manifest.json'))).toBe(true);
  });

  it('FAILs when manifest.json is invalid JSON', async () => {
    await mkdir(join(dir, '.gemini'), { recursive: true });
    await writeFile(join(dir, '.gemini', 'manifest.json'), '{not json', 'utf-8');
    const r = await pluginInitCmd([dir]);
    expect(r.code).toBe(1);
    expect(r.lines.some((l) => l.includes('not valid JSON'))).toBe(true);
  });

  it('writes a valid .claude-plugin/plugin.json with name + description from the manifest', async () => {
    await writeLegacyManifest({ name: 'my-legacy', description: 'old gemini' });
    const r = await pluginInitCmd([dir]);
    expect(r.code).toBe(0);
    const p = join(dir, '.claude-plugin', 'plugin.json');
    expect(existsSync(p)).toBe(true);
    const parsed = JSON.parse(await readFile(p, 'utf-8'));
    expect(parsed.name).toBe('my-legacy');
    expect(parsed.description).toBe('old gemini');
    expect(parsed.author.displayName).toBe('Generated by metaharness');
    expect(parsed.categories).toContain('agent-gemini');
    expect(parsed.categories).toContain('metaharness-scaffold');
    expect(parsed.tags).toContain('metaharness');
    expect(parsed.license).toBe('MIT');
  });

  it('per-vertical categories + tags when templateId is vertical:*', async () => {
    await writeLegacyManifest({ name: 'legacy-devops', templateId: 'vertical:devops', domain: 'devops/incident-response' });
    const r = await pluginInitCmd([dir]);
    expect(r.code).toBe(0);
    const parsed = JSON.parse(await readFile(join(dir, '.claude-plugin', 'plugin.json'), 'utf-8'));
    expect(parsed.categories).toContain('vertical');
    expect(parsed.categories).toContain('devops/incident-response');
    expect(parsed.tags).toContain('vertical:devops');
  });

  it('SKIPs when .claude-plugin/plugin.json already exists (idempotent)', async () => {
    await writeLegacyManifest();
    await mkdir(join(dir, '.claude-plugin'), { recursive: true });
    await writeFile(join(dir, '.claude-plugin', 'plugin.json'), '{"name":"existing"}', 'utf-8');
    const r = await pluginInitCmd([dir]);
    expect(r.code).toBe(0);
    expect(r.lines.some((l) => l.includes('SKIP'))).toBe(true);
    const after = JSON.parse(await readFile(join(dir, '.claude-plugin', 'plugin.json'), 'utf-8'));
    expect(after.name).toBe('existing');  // unchanged
  });

  it('--force overwrites an existing plugin.json', async () => {
    await writeLegacyManifest({ name: 'replacement' });
    await mkdir(join(dir, '.claude-plugin'), { recursive: true });
    await writeFile(join(dir, '.claude-plugin', 'plugin.json'), '{"name":"existing"}', 'utf-8');
    const r = await pluginInitCmd([dir, '--force']);
    expect(r.code).toBe(0);
    const after = JSON.parse(await readFile(join(dir, '.claude-plugin', 'plugin.json'), 'utf-8'));
    expect(after.name).toBe('replacement');
  });

  it('--dry-run reports the would-write path + preview, does not write', async () => {
    await writeLegacyManifest({ name: 'dryrun-bot' });
    const r = await pluginInitCmd([dir, '--dry-run']);
    expect(r.code).toBe(0);
    expect(r.lines.some((l) => l.includes('would-write'))).toBe(true);
    expect(r.lines.some((l) => l.includes('preview:'))).toBe(true);
    expect(existsSync(join(dir, '.claude-plugin', 'plugin.json'))).toBe(false);
  });

  it('tolerates legacy manifests with top-level name/description (pre-meta)', async () => {
    await mkdir(join(dir, '.gemini'), { recursive: true });
    await writeFile(join(dir, '.gemini', 'manifest.json'),
      JSON.stringify({ name: 'top-level-bot', description: 'old shape' }), 'utf-8');
    const r = await pluginInitCmd([dir]);
    expect(r.code).toBe(0);
    const parsed = JSON.parse(await readFile(join(dir, '.claude-plugin', 'plugin.json'), 'utf-8'));
    expect(parsed.name).toBe('top-level-bot');
    expect(parsed.description).toBe('old shape');
  });
});
